#! /usr/bin/env bash

set -Eeo pipefail

cd $(dirname "$(realpath "$0")")

cd /opt/rapids/raft/python/raft

pip-install-util \
    "cython>=0.29,<0.30" \
    "scikit-build>=0.13.1" \
    "cuda-python==$CUDA_VERSION" \
    "dask==2022.03.0" \
    "dask-cuda==22.04.0" \
    "distributed==2022.03.0"

(
    set -x;
    install-ucx-python;
)

on_exit() {
    ERRCODE="$?";
    unlink-sccache || true;
    exit "$ERRCODE";
}

trap on_exit ERR EXIT HUP INT QUIT TERM STOP PWR;

link-sccache

time (
    set -x;

    rm -rf build/python;
    mkdir -p build/python;

    env UCX_HOME=/usr/local/ucx \
        RMM_INCLUDE_DIR=/opt/rapids/rmm/include \
        THRUST_INCLUDE_DIR=/opt/rapids/rmm/build/_deps/thrust-src \
        SPDLOG_INCLUDE_DIR=/opt/rapids/rmm/build/_deps/spdlog-src/include \
    python setup.py \
        build_ext \
            --inplace \
            --parallel ${PARALLEL_LEVEL:-1} \
            --library-dir=/opt/rapids/raft/cpp/build \
        bdist_wheel \
            -d build/python;

    { set +x; } 2>/dev/null;

    mkdir -p /tmp/wheels && cp build/python/*.whl /tmp/wheels/

    mv build/lib.*/raft build/python/raft

    rm -rf *.egg-info build/{lib,temp,bdist}.*

    echo -n "pyraft build time:";
)
