#! /usr/bin/env bash

set -Eeo pipefail

time (
    set -x;
    cmake --build /opt/rapids/rmm/build -v -- -j${PARALLEL_LEVEL:-1} all;
    { set +x; } 2>/dev/null;
    echo -n "librmm compile time:";
)
