version: "3.8"

x-common-config: &common_config
  tty: true
  environment:
    # Colorize the terminal in the container if possible
    TERM: "${TERM:-}"

x-run-with-gpu: &run_with_gpu
  deploy:
    resources:
      reservations:
        devices:
          - capabilities:
            - gpu

services:
  01-base:
    image: pauletaylor/rapids-ide:cuda${CUDA_VERSION_MAJOR:-11}.${CUDA_VERSION_MINOR:-6}.${CUDA_VERSION_PATCH:-2}-${LINUX_DISTRO:-ubuntu20.04}
    build:
      context: compose/images/01-base
      args:
        LINUX_DISTRO: ${LINUX_DISTRO:-ubuntu20.04}
        CUDA_VERSION_MAJOR: ${CUDA_VERSION_MAJOR:-11}
        CUDA_VERSION_MINOR: ${CUDA_VERSION_MINOR:-6}
        CUDA_VERSION_PATCH: ${CUDA_VERSION_PATCH:-2}
    <<: *common_config
    <<: *run_with_gpu

  02-cpp:
    image: pauletaylor/rapids-ide:gcc${GCC_VERSION:-9}-cuda${CUDA_VERSION_MAJOR:-11}.${CUDA_VERSION_MINOR:-6}.${CUDA_VERSION_PATCH:-2}-${LINUX_DISTRO:-ubuntu20.04}
    build:
      context: compose/images/02-cpp
      args:
        GCC_VERSION: ${GCC_VERSION:-9}
        BASE_IMAGE: pauletaylor/rapids-ide:cuda${CUDA_VERSION_MAJOR:-11}.${CUDA_VERSION_MINOR:-6}.${CUDA_VERSION_PATCH:-2}-${LINUX_DISTRO:-ubuntu20.04}
    <<: *common_config
    <<: *run_with_gpu

  02-mamba:
    image: pauletaylor/rapids-ide:mamba${MAMBA_VERSION:-4.12.0-0}-python${PYTHON_VERSION:-3.9}-cuda${CUDA_VERSION_MAJOR:-11}.${CUDA_VERSION_MINOR:-6}.${CUDA_VERSION_PATCH:-2}-${LINUX_DISTRO:-ubuntu20.04}
    build:
      context: compose/images/02-mamba
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.9}
        MAMBA_VERSION: ${MAMBA_VERSION:-4.12.0-0}
        BASE_IMAGE: pauletaylor/rapids-ide:cuda${CUDA_VERSION_MAJOR:-11}.${CUDA_VERSION_MINOR:-6}.${CUDA_VERSION_PATCH:-2}-${LINUX_DISTRO:-ubuntu20.04}
    <<: *common_config
    <<: *run_with_gpu

  03-python:
    image: pauletaylor/rapids-ide:python${PYTHON_VERSION:-3.9}-gcc${GCC_VERSION:-9}-cuda${CUDA_VERSION_MAJOR:-11}.${CUDA_VERSION_MINOR:-6}.${CUDA_VERSION_PATCH:-2}-${LINUX_DISTRO:-ubuntu20.04}
    build:
      context: compose/images/03-python
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.9}
        BASE_IMAGE: pauletaylor/rapids-ide:gcc${GCC_VERSION:-9}-cuda${CUDA_VERSION_MAJOR:-11}.${CUDA_VERSION_MINOR:-6}.${CUDA_VERSION_PATCH:-2}-${LINUX_DISTRO:-ubuntu20.04}
    <<: *common_config
    <<: *run_with_gpu

  04-code-server:
    image: pauletaylor/rapids-ide:code-server${CODE_SERVER_VERSION:-4.4.0}-python${PYTHON_VERSION:-3.9}-mamba${MAMBA_VERSION:-4.12.0-0}-gcc${GCC_VERSION:-9}-cuda${CUDA_VERSION_MAJOR:-11}.${CUDA_VERSION_MINOR:-6}.${CUDA_VERSION_PATCH:-2}-${LINUX_DISTRO:-ubuntu20.04}
    build:
      context: compose/images/04-code-server
      args:
        LINUX_DISTRO: ${LINUX_DISTRO:-ubuntu20.04}
        GCC_VERSION: ${GCC_VERSION:-9}
        MAMBA_VERSION: ${MAMBA_VERSION:-4.12.0-0}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.9}
        CLANG_FORMAT_VERSION: ${CLANG_FORMAT_VERSION:-11}
        CUDA_VERSION_MAJOR: ${CUDA_VERSION_MAJOR:-11}
        CUDA_VERSION_MINOR: ${CUDA_VERSION_MINOR:-6}
        CUDA_VERSION_PATCH: ${CUDA_VERSION_PATCH:-2}
        CODE_SERVER_VERSION: ${CODE_SERVER_VERSION:-4.4.0}
        BASE_IMAGE: pauletaylor/rapids-ide:python${PYTHON_VERSION:-3.9}-gcc${GCC_VERSION:-9}-cuda${CUDA_VERSION_MAJOR:-11}.${CUDA_VERSION_MINOR:-6}.${CUDA_VERSION_PATCH:-2}-${LINUX_DISTRO:-ubuntu20.04}
        MAMBA_IMAGE: pauletaylor/rapids-ide:mamba${MAMBA_VERSION:-4.12.0-0}-python${PYTHON_VERSION:-3.9}-cuda${CUDA_VERSION_MAJOR:-11}.${CUDA_VERSION_MINOR:-6}.${CUDA_VERSION_PATCH:-2}-${LINUX_DISTRO:-ubuntu20.04}
    env_file: .env
    environment:
      # Colorize the terminal in the container if possible
      TERM: "${TERM:-}"
      # -e DOCKERD_GROUP=$(cat /etc/group | grep -F "docker:" | cut -d':' -f3)
      DOCKERD_GROUP: "${DOCKERD_GROUP:-998}"
      DOCKER_USER_HOME: "/tmp/code-server-home"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/code-server-home:/tmp/code-server-home"
      - "./compose/images/04-code-server/usr/local/bin/builder:/usr/local/bin/builder:ro"
      - "./compose/images/04-code-server/usr/local/bin/install-plugins:/usr/local/bin/install-plugins:ro"
      - "./compose/images/04-code-server/usr/local/bin/run-in-docker-build:/usr/local/bin/run-in-docker-build:ro"
    ports:
      - "8080:8080"
    command: --link
    <<: *run_with_gpu
