version: "3.8"

x-run-with-gpu: &run_with_gpu
  deploy:
    resources:
      reservations:
        devices:
          - capabilities:
            - gpu

services:

  cpp-builder:
    image: pauletaylor/rapids-ide:cpp-builder-cuda${CUDA_VERSION:-11.6.0}-ubuntu20.04
    build:
      context: compose/cpp-builder
      args:
        GCC_VERSION: ${GCC_VERSION:-9}
        UXC_VERSION: ${UXC_VERSION:-1.11}
        BASE_IMAGE: nvidia/cuda:${CUDA_VERSION:-11.6.0}-devel-ubuntu20.04
    # env_file: .env
    environment:
      # Colorize the terminal in the container if possible
      TERM: "${TERM:-}"
      NVIDIA_DRIVER_CAPABILITIES: all
    # volumes:
    #   - "./compose/cpp-builder/plugins:/opt/rapids/.plugins:ro"
    <<: *run_with_gpu

  code-server:
    image: pauletaylor/rapids-ide:code-server-4.2.0
    build:
      context: compose/code-server
      args:
        BASE_IMAGE: pauletaylor/rapids-ide:cpp-builder-cuda${CUDA_VERSION:-11.6.0}-ubuntu20.04
    # env_file: .env
    environment:
      # Colorize the terminal in the container if possible
      TERM: "${TERM:-}"
      NVIDIA_DRIVER_CAPABILITIES: all
      # -e DOCKERD_GROUP=$(cat /etc/group | grep -F "docker:" | cut -d':' -f3)
      DOCKERD_GROUP: "${DOCKERD_GROUP:-998}"
      DOCKER_USER_HOME: "${PWD}/compose/code-server/home"
    volumes:
      - "./compose/code-server/home:${PWD}/compose/code-server/home"
      # - "./compose/code-server/plugins:/opt/rapids/.plugins:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    <<: *run_with_gpu
    ports:
      - "8080:8080"
    command: --link
