version: "3.8"

x-run-with-gpu: &run_with_gpu
  deploy:
    resources:
      reservations:
        devices:
          - capabilities:
            - gpu

x-common-environment: &env_common
  # Colorize the terminal in the container if possible
  TERM: "${TERM:-}"
  NVIDIA_DRIVER_CAPABILITIES: all

services:

  cpp-builder:
    image: pauletaylor/rapids-ide:cpp-builder-cuda${CUDA_VERSION:-11.6.0}-ubuntu20.04
    build:
      context: compose/builder/cpp
      args:
        GCC_VERSION: ${GCC_VERSION:-9}
        UXC_VERSION: ${UXC_VERSION:-1.11}
        BASE_IMAGE: nvidia/cuda:${CUDA_VERSION:-11.6.0}-devel-ubuntu20.04
    environment:
      <<: *env_common
    volumes:
      - "./compose/builder/cpp/plugins:/opt/rapids/.plugins:ro"
    <<: *run_with_gpu

  conda-builder:
    image: pauletaylor/rapids-ide:conda-builder-cuda${CUDA_VERSION:-11.6.0}-ubuntu20.04
    build:
      context: compose/builder/conda
      args:
        BASE_IMAGE: nvidia/cuda:${CUDA_VERSION:-11.6.0}-base-ubuntu20.04
    environment:
      <<: *env_common
    volumes:
      - "./compose/builder/conda/plugins:/opt/rapids/.plugins:ro"
    <<: *run_with_gpu

  python-builder:
    image: pauletaylor/rapids-ide:python-builder-cuda${CUDA_VERSION:-11.6.0}-ubuntu20.04
    build:
      context: compose/builder/python
      args:
        BASE_IMAGE: pauletaylor/rapids-ide:cpp-builder-cuda${CUDA_VERSION:-11.6.0}-ubuntu20.04
    environment:
      <<: *env_common
    volumes:
      - "./compose/builder/python/plugins:/opt/rapids/.plugins:ro"
    <<: *run_with_gpu

  code-server:
    image: pauletaylor/rapids-ide:code-server-4.3.0-cuda${CUDA_VERSION:-11.6.0}-ubuntu20.04
    build:
      context: compose/code-server
      args:
        BASE_IMAGE: pauletaylor/rapids-ide:cpp-builder-cuda${CUDA_VERSION:-11.6.0}-ubuntu20.04
        PYTHON_IMAGE: pauletaylor/rapids-ide:python-builder-cuda${CUDA_VERSION:-11.6.0}-ubuntu20.04
    environment:
      <<: *env_common
      # -e DOCKERD_GROUP=$(cat /etc/group | grep -F "docker:" | cut -d':' -f3)
      DOCKERD_GROUP: "${DOCKERD_GROUP:-998}"
      DOCKER_USER_HOME: "${PWD}/compose/code-server/home"
    volumes:
      # - "./compose/code-server/plugins/util/make-repo-plugins:/opt/rapids/.plugins/util/make-repo-plugins:ro"
      - "./compose/code-server/home:${PWD}/compose/code-server/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    <<: *run_with_gpu
    ports:
      - "8080:8080"
    command: --link
