#! /usr/bin/env bash

set -Eeo pipefail

pids=

for repo in $(list-repos); do
    if [ -n $(which clean-$repo-cpp) ]; then
        echo "+ clean-$repo-cpp";
        bash -l <<< "clean-$repo-cpp" 2>/dev/null &
        pids="${pids:+$pids }$!"
    fi
done

if [[ -n "$pids" ]]; then
    wait ${pids};
fi
