#! /usr/bin/env bash

set -Eeo pipefail

cd $(dirname "$(realpath "$0")")

REPO_SRC="${RMM_SOURCE_DIR:-/opt/rapids/rmm}"
PYTHON_SRC="${RMM_PYTHON_SOURCE_DIR:-$REPO_SRC/python}"
PYTHON_BIN="${RMM_PYTHON_BINARY_DIR:-$PYTHON_SRC/build}"

rm -rf "$PYTHON_SRC/_skbuild" "$PYTHON_BIN";
find "$REPO_SRC" -type f -name '*.pyc' -delete;
find "$REPO_SRC" -type d -name '__pycache__' -delete;
find "$PYTHON_SRC" -type f -name '*.so' -delete;
find "$PYTHON_SRC" -type f -name '*.cpp' -delete;
if [[ -d "$PYTHON_SRC"/build ]]; then
    find "$PYTHON_SRC"/build -type d -empty -delete;
fi
