#! /usr/bin/env bash

set -Eeo pipefail

$(which build-rmm-cpp) && build-rmm-cpp || true;
$(which build-cudf-cpp) && build-cudf-cpp || true;
$(which build-raft-cpp) && build-raft-cpp || true;
$(which build-cumlprims_mg-cpp) && build-cumlprims_mg-cpp || true;
$(which build-cuml-cpp) && build-cuml-cpp || true;
$(which build-cugraph-ops-cpp) && build-cugraph-ops-cpp || true;
$(which build-cugraph-cpp) && build-cugraph-cpp || true;
$(which build-cuspatial-cpp) && build-cuspatial-cpp || true;
