#! /usr/bin/env bash

set -Eeo pipefail

pids=

for repo in $(list-projects); do
    if [ -n $(which clean-$repo-cpp) ]; then
        echo "+ clean-$repo-cpp";
        script -aqc "clean-$repo-cpp" /dev/null 1>/dev/null &
        pids="${pids:+$pids }$!"
    fi
done

if [[ -n "$pids" ]]; then
    wait ${pids};
fi
