#! /usr/bin/env bash

set -Eeo pipefail

rm -rf ${RAFT_CPP_BINARY_DIR:-$workspace/raft/cpp/build};
if [[ -d "${RAFT_CPP_SOURCE_DIR:-$workspace/raft/cpp}/build" ]]; then
    find "${RAFT_CPP_SOURCE_DIR:-$workspace/raft/cpp}/build" -type d -empty -delete;
fi
