#! /usr/bin/env bash

set -Eeo pipefail

time (
    set -x;
    cmake --build $workspace/raft/cpp/build -v -- -j${PARALLEL_LEVEL:-1} all;
    { set +x; } 2>/dev/null;
    echo -n "libraft compile time:";
)
