#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=cugraph \
    --url=${CUGRAPH_URL:-} \
    --out=${CUGRAPH_OUT:-} \
    --branch=${CUGRAPH_BRANCH:-} \
    --version=${CUGRAPH_VERSION:-}"

copy-inputs ${ARGS} \
 && configure-cugraph-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
