#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=cuml \
    --url=${CUML_URL:-} \
    --branch=${CUML_BRANCH:-} \
    --version=${CUML_VERSION:-} \
    --bin-out=${CUML_BINARY_DIR:-} \
    --src-out=${CUML_SOURCE_DIR:-}"

copy-inputs ${ARGS} \
 && configure-cuml-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
