#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=cumlprims_mg \
    --url=${CUMLPRIMS_MG_URL:-} \
    --out=${CUMLPRIMS_MG_OUT:-} \
    --branch=${CUMLPRIMS_MG_BRANCH:-} \
    --version=${CUMLPRIMS_MG_VERSION:-}"

copy-inputs ${ARGS} \
 && configure-cumlprims_mg-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
