#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=cugraph-ops \
    --url=${CUGRAPH_OPS_URL:-} \
    --branch=${CUGRAPH_OPS_BRANCH:-} \
    --version=${CUGRAPH_OPS_VERSION:-} \
    --bin-out=${CUGRAPH_OPS_BINARY_DIR:-} \
    --src-out=${CUGRAPH_OPS_SOURCE_DIR:-}"

copy-inputs ${ARGS} \
 && configure-cugraph-ops-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
