#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=rmm \
    --url=${RMM_URL:-} \
    --out=${RMM_OUT:-} \
    --branch=${RMM_BRANCH:-} \
    --version=${RMM_VERSION:-}"

copy-inputs ${ARGS} \
 && configure-rmm-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
