#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=cudf \
    --url=${CUDF_URL:-} \
    --out=${CUDF_OUT:-} \
    --branch=${CUDF_BRANCH:-} \
    --version=${CUDF_VERSION:-}"

copy-inputs ${ARGS} \
 && configure-cudf-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
