#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=rmm \
    --url=${RMM_URL:-} \
    --branch=${RMM_BRANCH:-} \
    --version=${RMM_VERSION:-} \
    --bin-out=${RMM_BINARY_DIR:-} \
    --src-out=${RMM_SOURCE_DIR:-}"

copy-inputs ${ARGS} \
 && configure-rmm-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
