#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=cumlprims_mg \
    --url=${CUMLPRIMS_MG_URL:-} \
    --branch=${CUMLPRIMS_MG_BRANCH:-} \
    --version=${CUMLPRIMS_MG_VERSION:-} \
    --bin-out=${CUMLPRIMS_MG_BINARY_DIR:-} \
    --src-out=${CUMLPRIMS_MG_SOURCE_DIR:-}"

copy-inputs ${ARGS} \
 && configure-cumlprims_mg-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
