#! /usr/bin/env bash

set -Eeo pipefail

BUILD_BENCH=${BUILD_BENCH:-OFF}
BUILD_TESTS=${BUILD_TESTS:-OFF}
CUDA_LINEINFO=${CUDA_LINEINFO:-OFF}
DISABLE_DEPRECATION_WARNINGS=${DISABLE_DEPRECATION_WARNINGS:-ON}

configure-cpp \
    --project=cudf \
    --url="${CUDF_URL:-}" \
    --branch="${CUDF_BRANCH:-}" \
    \
    -D rmm_ROOT="$(cpp-binary-dir --project=rmm)" \
    \
    -D CUDF_ENABLE_ARROW_S3=OFF \
    -D BUILD_TESTS=${BUILD_TESTS} \
    -D BUILD_BENCHMARKS=${BUILD_BENCH} \
    -D DISABLE_DEPRECATION_WARNING=${DISABLE_DEPRECATION_WARNINGS} \
    \
    -D CUDA_ENABLE_LINEINFO=${CUDA_LINEINFO} \
    \
    ${@};
