#! /usr/bin/env bash

set -Eeo pipefail

BUILD_TESTS=${BUILD_TESTS:-OFF}
CUDA_LINEINFO=${CUDA_LINEINFO:-OFF}
CUDA_KERNELINFO=${CUDA_KERNELINFO:-OFF}
DISABLE_DEPRECATION_WARNINGS=${DISABLE_DEPRECATION_WARNINGS:-ON}

configure-cpp \
    --project=raft \
    --url="${RAFT_URL:-}" \
    --out="${RAFT_OUT:-}" \
    --branch="${RAFT_BRANCH:-}" \
    \
    -D rmm_ROOT="$(cpp-binary-dir --project=rmm)" \
    \
    -D DETECT_CONDA_ENV=OFF \
    \
    -D RAFT_COMPILE_LIBRARIES=ON \
    \
    -D BUILD_TESTS=${BUILD_TESTS} \
    -D DISABLE_DEPRECATION_WARNINGS=${DISABLE_DEPRECATION_WARNINGS} \
    \
    -D CUDA_ENABLE_LINEINFO=${CUDA_LINEINFO} \
    -D CUDA_ENABLE_KERNELINFO=${CUDA_KERNELINFO} \
    \
    ${@};
