#! /usr/bin/env bash
set -Eeo pipefail;
cd "$(dirname "$(realpath "$0")")";
if [[ -d "$HOME/rapids/rmm" ]]; then

    tmp_env_file="$(mktemp)";
    touch "$HOME/rapids/.config/cpp.env" "$tmp_env_file";

    cat "$HOME/rapids/.config/cpp.env" >> "$tmp_env_file";

    if [ -n ${BUILD_TYPE:-} ]; then
        echo "BUILD_TYPE=$BUILD_TYPE" >> "$tmp_env_file";
        sed -ir "s/^BUILD_TYPE=\w+\$/BUILD_TYPE=$BUILD_TYPE/g" "$tmp_env_file";
    fi
    if [ -n ${BUILD_TESTS:-} ]; then
        echo "BUILD_TESTS=$BUILD_TESTS" >> "$tmp_env_file";
        sed -ir "s/^BUILD_TESTS=\w+\$/BUILD_TESTS=$BUILD_TESTS/g" "$tmp_env_file";
    fi
    if [ -n ${BUILD_BENCH:-} ]; then
        echo "BUILD_BENCH=$BUILD_BENCH" >> "$tmp_env_file";
        sed -ir "s/^BUILD_BENCH=\w+\$/BUILD_BENCH=$BUILD_BENCH/g" "$tmp_env_file";
    fi

    on_exit() {
        ERRCODE="$?";
        rm -f "$tmp_env_file" >/dev/null 2>&1 || true;
        exit "$ERRCODE";
    }

    trap on_exit ERR EXIT HUP INT QUIT TERM STOP PWR;

    (
    set -a && source "$tmp_env_file" && set +a;

    if [[ -d "$HOME/rapids/rmm" ]]; then
        echo "RMM_SOURCE_DIR=$HOME/rapids/rmm" >> "$tmp_env_file";
        echo "RMM_CPP_SOURCE_DIR=$(cpp-source-dir-util --project=rmm)" >> "$tmp_env_file";
        echo "RMM_CPP_BINARY_DIR=$(cpp-binary-dir-util --project=rmm)" >> "$tmp_env_file";
    fi

    volumes="";
    if [[ -d "$HOME/rapids/rmm" ]]; then volumes+="-v $HOME/rapids/rmm:$HOME/rapids/rmm "; fi

    docker run \
        --rm -it --runtime nvidia \
        --env-file "$tmp_env_file" \
        --name "clean-rmm-cpp-$(basename "$tmp_env_file")" \
        ${volumes} \
        pauletaylor/rapids-ide:cpp-builder-cuda11.6.0-ubuntu20.04 \
        bash -c '
        clean-rmm-cpp;' _ "${@}";
    )
fi
