#! /usr/bin/env bash
set -Eeo pipefail;
cd "$(dirname "$(realpath "$0")")";

GHHOSTS="$HOME/.config/gh/hosts.yml";

if [[ ! -f "$GHHOSTS" ]]; then gh auth login; fi

GH_USER="$(grep --color=never 'user:' "$GHHOSTS" | cut -d ':' -f2 | tr -d '[:space:]')";

if [[ -n "$GH_USER" && ! -d "$HOME/rapids/rmm" ]]; then

    REPO="$GH_USER/rmm";
    FORK="$(gh repo list $GH_USER --fork --json name --jq '. | map(select(.name == "rmm")) | map(.name)[]')";
    if [[ ! "$FORK" ]]; then
        ORIGIN_URL="github.com/$GH_USER/rmm";
        UPSTREAM_URL="github.com/rapidsai/rmm";
        while true; do
            read -p "\`$UPSTREAM_URL\` not found.
Fork \`\` into \`$ORIGIN_URL\` now (y/n)? " CHOICE </dev/tty
            case $CHOICE in
                [Nn]* ) REPO="rapidsai/rmm"; break;;
                [Yy]* ) gh repo fork rapidsai/rmm --clone=false; break;;
                * ) echo "Please answer 'y' or 'n'";;
            esac
        done;
    fi
    gh repo clone $REPO "$HOME/rapids/rmm";
fi
