#! /usr/bin/env bash

set -Eeou pipefail

time (
    set -x;
    cmake --build /opt/rapids/cudf/cpp/build -v -- -j${PARALLEL_LEVEL:-1} all;
    { set +x; } 2>/dev/null;
    echo "libcudf compile time:";
)
