#! /usr/bin/env bash

set -Eeou pipefail

cd $(dirname "$(realpath "$0")")

PROJECT=
EXTERNAL_SOURCE_DIR=
EXTERNAL_CPP_BINARY_DIR=

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --project=*) PROJECT="${1#--project=}";;
        --src=*) EXTERNAL_SOURCE_DIR="${1#--src=}";;
        --bin=*) EXTERNAL_CPP_BINARY_DIR="${1#--bin=}";;
        *) ;;
    esac; shift;
done

if [[ ! -n "$EXTERNAL_SOURCE_DIR" || ! -d "$EXTERNAL_SOURCE_DIR" ]]; then
    exit 1;
fi

INTERNAL_SOURCE_DIR="/opt/rapids/$PROJECT";

# Copy external source dir to internal source dir
(
    mkdir -p "$INTERNAL_SOURCE_DIR";
    cp -ar "$EXTERNAL_SOURCE_DIR"/* "$INTERNAL_SOURCE_DIR"/;
) || true;

INTERNAL_CPP_SOURCE_DIR="$(cpp-source-dir-util --project="$PROJECT")";
INTERNAL_CPP_BINARY_DIR="$(cpp-binary-dir-util --project="$PROJECT")";

if [[ ! -n "$INTERNAL_CPP_SOURCE_DIR" ]]; then
    exit 1;
fi

J=$(nproc --ignore=2)

if [[ -z "$INTERNAL_CPP_BINARY_DIR" ]]; then
    INTERNAL_CPP_BINARY_DIR="$INTERNAL_CPP_SOURCE_DIR/build";
fi

mkdir -p "$INTERNAL_CPP_SOURCE_DIR";
mkdir -p "$INTERNAL_CPP_BINARY_DIR";

# Move the build dir from its external location to its inner location
(
    SUF="$(realpath -m --relative-to="$EXTERNAL_SOURCE_DIR" "$EXTERNAL_CPP_BINARY_DIR")"
    mkdir -p "$INTERNAL_SOURCE_DIR/$SUF";
    if [[ -d "$INTERNAL_SOURCE_DIR/$SUF" ]]; then
        tmp_dir="$(mktemp -d)";
        mv "$INTERNAL_SOURCE_DIR/$SUF" "$tmp_dir/build";
        rm -rf "$INTERNAL_CPP_BINARY_DIR";
        mv "$tmp_dir/build" "$INTERNAL_CPP_BINARY_DIR";
        rm -rf "$tmp_dir";
    fi
) || true;
