#! /usr/bin/env bash

set -Eeo pipefail

rm -rf ${CUDF_CPP_BINARY_DIR:-$workspace/cudf/cpp/build};
if [[ -d "${CUDF_CPP_SOURCE_DIR:-$workspace/cudf/cpp}/build" ]]; then
    find "${CUDF_CPP_SOURCE_DIR:-$workspace/cudf/cpp}/build" -type d -empty -delete;
fi
