#! /usr/bin/env bash

set -Eeo pipefail

PROJECT=

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --project=*) PROJECT="${1#--project=}";;
        *) ;;
    esac; shift;
done

CPP_DIR="$HOME/$PROJECT"

if [[ -d "$CPP_DIR/cpp" ]]; then
    CPP_DIR="$CPP_DIR/cpp"
fi

while true; do
    if [[ -f "$CPP_DIR/CMakeLists.txt" ]]; then
        break;
    elif [[ "$CPP_DIR" == "$HOME/$PROJECT" ]]; then
        break;
    fi
    CPP_DIR=$(realpath -m "$CPP_DIR/..")
done

echo "$CPP_DIR"
