#! /usr/bin/env bash

set -Eeo pipefail

PROJECT=

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --project=*) PROJECT="${1#--project=}";;
        *) ;;
    esac; shift;
done

prefix="$(python-source-dir-util --project=$PROJECT)/build/cuda-$CUDA_VERSION";
branch_name="$(git -C "$HOME/$PROJECT" branch --show-current)";
echo "$prefix/${branch_name//\//__}/${PYTHON_BUILDER:-wheel}";
