#! /usr/bin/env bash

set -Eeo pipefail

PROJECT=

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --project=*) PROJECT="${1#--project=}";;
        *) ;;
    esac; shift;
done

PYTHON_DIR="$HOME/$PROJECT"

if [[ -d "$PYTHON_DIR/python" ]]; then
    PYTHON_DIR="$PYTHON_DIR/python"
fi

PYTHON_DIR="$PYTHON_DIR/$PROJECT"

while true; do
    if [[ -f "$PYTHON_DIR/setup.py" ]]; then
        break;
    elif [[ "$PYTHON_DIR" == "$HOME/$PROJECT" ]]; then
        break;
    fi
    PYTHON_DIR=$(realpath -m "$PYTHON_DIR/..")
done

echo "$PYTHON_DIR"
