#! /usr/bin/env bash
set -Eeo pipefail;
cd "$(dirname "$(realpath "$0")")";
if [[ -d "$HOME/rapids/cuml" ]]; then

    tmp_env_file="$(mktemp)";
    touch "$HOME/rapids/.config/cpp.env" "$tmp_env_file";

    cat "$HOME/rapids/.config/cpp.env" >> "$tmp_env_file";

    if [ -n ${BUILD_TYPE:-} ]; then
        echo "BUILD_TYPE=$BUILD_TYPE" >> "$tmp_env_file";
        sed -ir "s/^BUILD_TYPE=\w+\$/BUILD_TYPE=$BUILD_TYPE/g" "$tmp_env_file";
    fi
    if [ -n ${BUILD_TESTS:-} ]; then
        echo "BUILD_TESTS=$BUILD_TESTS" >> "$tmp_env_file";
        sed -ir "s/^BUILD_TESTS=\w+\$/BUILD_TESTS=$BUILD_TESTS/g" "$tmp_env_file";
    fi
    if [ -n ${BUILD_BENCH:-} ]; then
        echo "BUILD_BENCH=$BUILD_BENCH" >> "$tmp_env_file";
        sed -ir "s/^BUILD_BENCH=\w+\$/BUILD_BENCH=$BUILD_BENCH/g" "$tmp_env_file";
    fi

    on_exit() {
        ERRCODE="$?";
        rm -f "$tmp_env_file" >/dev/null 2>&1 || true;
        exit "$ERRCODE";
    }

    trap on_exit ERR EXIT HUP INT QUIT TERM STOP PWR;

    (
    set -a && source "$tmp_env_file" && set +a;

    if [[ -d "$HOME/rapids/cuml" ]]; then
        echo "CUML_SOURCE_DIR=$HOME/rapids/cuml" >> "$tmp_env_file";
        echo "CUML_CPP_SOURCE_DIR=$(cpp-source-dir-util --project=cuml)" >> "$tmp_env_file";
        echo "CUML_CPP_BINARY_DIR=$(cpp-binary-dir-util --project=cuml)" >> "$tmp_env_file";
    fi
    if [[ -d "$HOME/rapids/rmm" ]]; then
        echo "RMM_SOURCE_DIR=$HOME/rapids/rmm" >> "$tmp_env_file";
        echo "RMM_CPP_SOURCE_DIR=$(cpp-source-dir-util --project=rmm)" >> "$tmp_env_file";
        echo "RMM_CPP_BINARY_DIR=$(cpp-binary-dir-util --project=rmm)" >> "$tmp_env_file";
    fi
    if [[ -d "$HOME/rapids/raft" ]]; then
        echo "RAFT_SOURCE_DIR=$HOME/rapids/raft" >> "$tmp_env_file";
        echo "RAFT_CPP_SOURCE_DIR=$(cpp-source-dir-util --project=raft)" >> "$tmp_env_file";
        echo "RAFT_CPP_BINARY_DIR=$(cpp-binary-dir-util --project=raft)" >> "$tmp_env_file";
    fi
    if [[ -d "$HOME/rapids/cumlprims_mg" ]]; then
        echo "CUMLPRIMS_MG_SOURCE_DIR=$HOME/rapids/cumlprims_mg" >> "$tmp_env_file";
        echo "CUMLPRIMS_MG_CPP_SOURCE_DIR=$(cpp-source-dir-util --project=cumlprims_mg)" >> "$tmp_env_file";
        echo "CUMLPRIMS_MG_CPP_BINARY_DIR=$(cpp-binary-dir-util --project=cumlprims_mg)" >> "$tmp_env_file";
    fi

    volumes="";
    if [[ -d "$HOME/rapids/cuml" ]]; then volumes+="-v $HOME/rapids/cuml:$HOME/rapids/cuml "; fi
    if [[ -d "$HOME/rapids/rmm" ]]; then volumes+="-v $HOME/rapids/rmm:$HOME/rapids/rmm:ro "; fi
    if [[ -d "$HOME/rapids/raft" ]]; then volumes+="-v $HOME/rapids/raft:$HOME/rapids/raft:ro "; fi
    if [[ -d "$HOME/rapids/cumlprims_mg" ]]; then volumes+="-v $HOME/rapids/cumlprims_mg:$HOME/rapids/cumlprims_mg:ro "; fi

    set -x;
    docker run \
        --rm -it --runtime nvidia \
        --env-file "$tmp_env_file" \
        --name "compile-cuml-cpp-$(basename "$tmp_env_file")" \
        ${volumes} \
        pauletaylor/rapids-ide:cpp-builder-cuda11.6.0-ubuntu20.04 \
        bash -c '
        pids=""; \
        bash -l <<< "copy-inputs-util --project=\"rmm\" --src=\"\$RMM_SOURCE_DIR\" --bin=\"\$RMM_CPP_BINARY_DIR\"" & \
        pids="${pids:+$pids }$!";
        bash -l <<< "copy-inputs-util --project=\"raft\" --src=\"\$RAFT_SOURCE_DIR\" --bin=\"\$RAFT_CPP_BINARY_DIR\"" & \
        pids="${pids:+$pids }$!";
        bash -l <<< "copy-inputs-util --project=\"cumlprims_mg\" --src=\"\$CUMLPRIMS_MG_SOURCE_DIR\" --bin=\"\$CUMLPRIMS_MG_CPP_BINARY_DIR\"" & \
        pids="${pids:+$pids }$!";
        bash -l <<< "copy-inputs-util --project=\"cuml\" --src=\"\$CUML_SOURCE_DIR\" --bin=\"\$CUML_CPP_BINARY_DIR\"" & \
        pids="${pids:+$pids }$!";
        wait ${pids}; \
        compile-cuml-cpp "${@}" 2>&1 \
          | sed -r "s@/opt/rapids/rmm/build@$RMM_CPP_BINARY_DIR@g" \
          | sed -r "s@$(realpath -m "/opt/rapids/rmm/$(realpath -m --relative-to="$RMM_SOURCE_DIR" "$RMM_CPP_SOURCE_DIR")")@$RMM_CPP_SOURCE_DIR@g" \
          | sed -r "s@ build/@ $(realpath -m --relative-to="$RMM_CPP_SOURCE_DIR" "$RMM_CPP_BINARY_DIR")/@g" \
          | sed -r "s@/opt/rapids/raft/build@$RAFT_CPP_BINARY_DIR@g" \
          | sed -r "s@$(realpath -m "/opt/rapids/raft/$(realpath -m --relative-to="$RAFT_SOURCE_DIR" "$RAFT_CPP_SOURCE_DIR")")@$RAFT_CPP_SOURCE_DIR@g" \
          | sed -r "s@ build/@ $(realpath -m --relative-to="$RAFT_CPP_SOURCE_DIR" "$RAFT_CPP_BINARY_DIR")/@g" \
          | sed -r "s@/opt/rapids/cumlprims_mg/build@$CUMLPRIMS_MG_CPP_BINARY_DIR@g" \
          | sed -r "s@$(realpath -m "/opt/rapids/cumlprims_mg/$(realpath -m --relative-to="$CUMLPRIMS_MG_SOURCE_DIR" "$CUMLPRIMS_MG_CPP_SOURCE_DIR")")@$CUMLPRIMS_MG_CPP_SOURCE_DIR@g" \
          | sed -r "s@ build/@ $(realpath -m --relative-to="$CUMLPRIMS_MG_CPP_SOURCE_DIR" "$CUMLPRIMS_MG_CPP_BINARY_DIR")/@g" \
          | sed -r "s@/opt/rapids/cuml/build@$CUML_CPP_BINARY_DIR@g" \
          | sed -r "s@$(realpath -m "/opt/rapids/cuml/$(realpath -m --relative-to="$CUML_SOURCE_DIR" "$CUML_CPP_SOURCE_DIR")")@$CUML_CPP_SOURCE_DIR@g" \
          | sed -r "s@ build/@ $(realpath -m --relative-to="$CUML_CPP_SOURCE_DIR" "$CUML_CPP_BINARY_DIR")/@g"; \
        copy-output-util --project="cuml" --src="$CUML_CPP_SOURCE_DIR" --bin="$CUML_CPP_BINARY_DIR";' _ "${@}";
    )
fi
