#! /usr/bin/env bash
set -Eeo pipefail;
cd "$(dirname "$(realpath "$0")")";
if [[ -d "$HOME/rapids/cumlprims_mg" ]]; then

    tmp_env_file="$(mktemp)";
    touch "$HOME/rapids/.env";
    cp "$HOME/rapids/.env" "$tmp_env_file";

    on_exit() {
        ERRCODE="$?";
        rm -f "$tmp_env_file" >/dev/null 2>&1 || true;
        exit "$ERRCODE";
    }

    trap on_exit ERR EXIT HUP INT QUIT TERM STOP PWR;

    set -a && . "$tmp_env_file" && set +a;

    
    if [[ -d "$HOME/rapids/cumlprims_mg" ]]; then
        echo "CUMLPRIMS_MG_SOURCE_DIR=$HOME/rapids/cumlprims_mg" >> "$tmp_env_file";
        echo "CUMLPRIMS_MG_CPP_SOURCE_DIR=$(cpp-source-dir-util --project=cumlprims_mg)" >> "$tmp_env_file";
        echo "CUMLPRIMS_MG_CPP_BINARY_DIR=$(cpp-binary-dir-util --project=cumlprims_mg)" >> "$tmp_env_file";
    fi

    volumes="";
    if [[ -d "$HOME/rapids/cumlprims_mg" ]]; then volumes+="-v $HOME/rapids/cumlprims_mg:$HOME/rapids/cumlprims_mg "; fi

    docker run \
        --rm -it --runtime nvidia \
        --env-file "$tmp_env_file" \
        ${volumes} \
        pauletaylor/rapids-ide:cpp-builder-cuda11.6.0-ubuntu20.04 \
        bash -c '
        clean-cumlprims_mg-cpp;' _ "${@}";
fi
