#! /usr/bin/env bash
set -Eeo pipefail;
cd "$(dirname "$(realpath "$0")")";
if [[ -d "$HOME/rapids/cumlprims_mg" ]]; then

    tmp_env_file="$(mktemp)";
    touch "$HOME/rapids/.env";
    cp "$HOME/rapids/.env" "$tmp_env_file";

    on_exit() {
        ERRCODE="$?";
        rm -f "$tmp_env_file" >/dev/null 2>&1 || true;
        exit "$ERRCODE";
    }

    trap on_exit ERR EXIT HUP INT QUIT TERM STOP PWR;

    set -a && . "$tmp_env_file" && set +a;

    
    if [[ -d "$HOME/rapids/rmm" ]]; then
        echo "RMM_SOURCE_DIR=$HOME/rapids/rmm" >> "$tmp_env_file";
        echo "RMM_CPP_SOURCE_DIR=$(cpp-source-dir-util --project=rmm)" >> "$tmp_env_file";
        echo "RMM_CPP_BINARY_DIR=$(cpp-binary-dir-util --project=rmm)" >> "$tmp_env_file";
    fi
    if [[ -d "$HOME/rapids/raft" ]]; then
        echo "RAFT_SOURCE_DIR=$HOME/rapids/raft" >> "$tmp_env_file";
        echo "RAFT_CPP_SOURCE_DIR=$(cpp-source-dir-util --project=raft)" >> "$tmp_env_file";
        echo "RAFT_CPP_BINARY_DIR=$(cpp-binary-dir-util --project=raft)" >> "$tmp_env_file";
    fi
    if [[ -d "$HOME/rapids/cumlprims_mg" ]]; then
        echo "CUMLPRIMS_MG_SOURCE_DIR=$HOME/rapids/cumlprims_mg" >> "$tmp_env_file";
        echo "CUMLPRIMS_MG_CPP_SOURCE_DIR=$(cpp-source-dir-util --project=cumlprims_mg)" >> "$tmp_env_file";
        echo "CUMLPRIMS_MG_CPP_BINARY_DIR=$(cpp-binary-dir-util --project=cumlprims_mg)" >> "$tmp_env_file";
    fi

    volumes="";
    if [[ -d "$HOME/rapids/rmm" ]]; then volumes+="-v $HOME/rapids/rmm:$HOME/rapids/rmm "; fi
    if [[ -d "$HOME/rapids/raft" ]]; then volumes+="-v $HOME/rapids/raft:$HOME/rapids/raft:ro "; fi
    if [[ -d "$HOME/rapids/cumlprims_mg" ]]; then volumes+="-v $HOME/rapids/cumlprims_mg:$HOME/rapids/cumlprims_mg:ro "; fi

    docker run \
        --rm -it --runtime nvidia \
        --env-file "$tmp_env_file" \
        ${volumes} \
        pauletaylor/rapids-ide:cpp-builder-cuda11.6.0-ubuntu20.04 \
        bash -c '
        pids=""; \
        bash -l <<< "copy-inputs-util --project=\"rmm\" --src=\"\$RMM_SOURCE_DIR\" --bin=\"\$RMM_CPP_BINARY_DIR\"" & \
        pids="${pids:+$pids }$!";
        bash -l <<< "copy-inputs-util --project=\"raft\" --src=\"\$RAFT_SOURCE_DIR\" --bin=\"\$RAFT_CPP_BINARY_DIR\"" & \
        pids="${pids:+$pids }$!";
        bash -l <<< "copy-inputs-util --project=\"cumlprims_mg\" --src=\"\$CUMLPRIMS_MG_SOURCE_DIR\" --bin=\"\$CUMLPRIMS_MG_CPP_BINARY_DIR\"" & \
        pids="${pids:+$pids }$!";
        wait ${pids}; \
        compile-cumlprims_mg-cpp "${@}"; \
        copy-output-util --project="cumlprims_mg" --src="$CUMLPRIMS_MG_CPP_SOURCE_DIR" --bin="$CUMLPRIMS_MG_CPP_BINARY_DIR";' _ "${@}";
fi
