#! /usr/bin/env bash

set -Eeo pipefail

rm -rf ${CUGRAPH_OPS_CPP_BINARY_DIR:-$workspace/cugraph-ops/build};
if [[ -d "${CUGRAPH_OPS_CPP_SOURCE_DIR:-$workspace/cugraph-ops}/build" ]]; then
    find "${CUGRAPH_OPS_CPP_SOURCE_DIR:-$workspace/cugraph-ops}/build" -type d -empty -delete;
fi
