#! /usr/bin/env bash

set -Eeo pipefail

cd $(dirname "$(realpath "$0")")

cd /opt/rapids/rmm/python

pkgs=
list="$(pip list)"
pkgs+="$([ -n "$(echo "$list" | grep -i cython)"       ] && echo "" || echo "cython>=0.29,<0.30 ")"
pkgs+="$([ -n "$(echo "$list" | grep -i numba)"        ] && echo "" || echo "numba>=0.54.0 ")"
pkgs+="$([ -n "$(echo "$list" | grep -i scikit-build)" ] && echo "" || echo "scikit-build>=0.13.1 ")"
pkgs+="$([ -n "$(echo "$list" | grep -i cuda-python)"  ] && echo "" || echo "cuda-python==$CUDA_VERSION ")"

if [[ -n "$pkgs" ]]; then
time (
    set -x;
    pip download --no-cache-dir --disable-pip-version-check --no-deps -d /tmp/pkgs ${pkgs};
    pip install  --no-cache-dir --disable-pip-version-check --upgrade /tmp/pkgs/*.whl;
    { set +x; } 2>/dev/null;
    echo -n "Pip install time:";
)
fi

time (
    set -x;

    python setup.py \
        -G Ninja --skip-generator-test \
    bdist_wheel \
     -- -D FIND_RMM_CPP=ON \
        -D RMM_ROOT=/opt/rapids/rmm/build \
        -D CMAKE_C_COMPILER_LAUNCHER=/usr/local/bin/sccache \
        -D CMAKE_CXX_COMPILER_LAUNCHER=/usr/local/bin/sccache \
        -D CMAKE_CUDA_COMPILER_LAUNCHER=/usr/local/bin/sccache \
     -- -j ${PARALLEL_LEVEL:-1};

    { set +x; } 2>/dev/null;

    mv _skbuild/*/cmake-install/rmm build/python/
    python setup.py clean;
    rm -rf _skbuild dist rmm.egg-info

    echo -n "RMM build time:";
)
