#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=raft \
    --url=${RAFT_URL:-} \
    --branch=${RAFT_BRANCH:-} \
    --version=${RAFT_VERSION:-} \
    --bin-out=${RAFT_BINARY_DIR:-} \
    --src-out=${RAFT_SOURCE_DIR:-}"

copy-inputs ${ARGS} \
 && configure-raft-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
