#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=cugraph \
    --url=${CUGRAPH_URL:-} \
    --branch=${CUGRAPH_BRANCH:-} \
    --version=${CUGRAPH_VERSION:-} \
    --bin-out=${CUGRAPH_BINARY_DIR:-} \
    --src-out=${CUGRAPH_SOURCE_DIR:-}"

copy-inputs ${ARGS} \
 && configure-cugraph-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
