#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=cudf \
    --url=${CUDF_URL:-} \
    --branch=${CUDF_BRANCH:-} \
    --version=${CUDF_VERSION:-} \
    --bin-out=${CUDF_BINARY_DIR:-} \
    --src-out=${CUDF_SOURCE_DIR:-}"

copy-inputs ${ARGS} \
 && configure-cudf-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
