#! /usr/bin/env bash

set -Eeo pipefail

ARGS="\
    --project=cuspatial \
    --url=${CUSPATIAL_URL:-} \
    --branch=${CUSPATIAL_BRANCH:-} \
    --version=${CUSPATIAL_VERSION:-} \
    --bin-out=${CUSPATIAL_BINARY_DIR:-} \
    --src-out=${CUSPATIAL_SOURCE_DIR:-}"

copy-inputs ${ARGS} \
 && configure-cuspatial-cpp ${@} \
 && compile-cpp ${ARGS} \
 && copy-output ${ARGS}
