#! /usr/bin/env bash

set -Eeo pipefail

CUDA_LINEINFO=${CUDA_LINEINFO:-OFF}
CUDA_KERNELINFO=${CUDA_KERNELINFO:-OFF}

configure-cpp \
    --project=cumlprims_mg \
    --url="${CUMLPRIMS_MG_URL:-}" \
    --branch="${CUMLPRIMS_MG_BRANCH:-}" \
    \
    -D raft_ROOT="$(cpp-binary-dir --project=raft)" \
    \
    -D DETECT_CONDA_ENV=OFF \
    -D DISABLE_FORCE_CLONE_RAFT=ON \
    \
    -D BUILD_TESTS=OFF \
    \
    -D CUDA_ENABLE_LINEINFO=${CUDA_LINEINFO} \
    -D CUDA_ENABLE_KERNELINFO=${CUDA_KERNELINFO} \
    \
    ${@};
