#! /usr/bin/env bash

set -Eeo pipefail

if [ -n $(which compile-rmm-cpp) ] then compile-rmm-cpp; fi;
if [ -n $(which compile-cudf-cpp) ] then compile-cudf-cpp; fi;
if [ -n $(which compile-raft-cpp) ] then compile-raft-cpp; fi;
if [ -n $(which compile-cumlprims_mg-cpp) ] then compile-cumlprims_mg-cpp; fi;
if [ -n $(which compile-cuml-cpp) ] then compile-cuml-cpp; fi;
if [ -n $(which compile-cugraph-ops-cpp) ] then compile-cugraph-ops-cpp; fi;
if [ -n $(which compile-cugraph-cpp) ] then compile-cugraph-cpp; fi;
if [ -n $(which compile-cuspatial-cpp) ] then compile-cuspatial-cpp; fi;
